# Version 0.10
#
- hosts: OneViewManagedBmcs
  connection: local
  gather_facts: False

  tasks:
      - name: Insert Virtual Media
        community.general.redfish_command:
            category: Manager
            command: VirtualMediaInsert
            baseuri: "{{ inventory_hostname }}:{{ ansible_port }}"
            username: "{{ username }}"
            password: "{{ password }}"
            virtual_media:
                image_url: 'http://example.com/images/SomeLinux-current.iso'
                media_types:
                   - CD
                   - DVD
            resource_id: "1"