# Version 0.10
#
- hosts: OneViewManagedBmcs
  connection: local
  gather_facts: False

  tasks:
      - name: Set chassis indicator LED to blink
        community.general.redfish_command:
            category: Chassis
            command: IndicatorLedBlink
            resource_id: "1"
            baseuri: "{{ inventory_hostname }}:{{ ansible_port }}"
            username: "{{ username }}"
            password: "{{ password }}"
        register: result
        
      - debug: 
           msg: "{{ result }}"