# Version 0.114
#
- hosts: OneViewManagedBmcs
  vars:
      username: "foo"
      password: "bar"
  connection: local
  gather_facts: False

  tasks:
      - name: 1.0- redfish_info: Retrieve Indicator LEDs status
        community.general.redfish_info:
             category: Chassis
             command: GetChassisInventory
             baseuri: "{{ inventory_hostname }}:{{ ansible_port }}"
             username: "{{ username }}"
             password: "{{ password }}"
        register: ChassisInventory
             
      - debug:
           msg: "{{ ChassisInventory.redfish_facts.chassis.entries | json_query('[].{Id: Id, ChassisType: ChassisType, IndicatorLED: IndicatorLED}') }}"
      
      
      - name: 1.1 Save indicator LEDs values
        set_fact:
            ChassisLEDValues: "{{ ChassisInventory.redfish_facts.chassis.entries | json_query('[].{Id: Id, IndicatorLED: IndicatorLED}') }}"
      
      - name: 2.0- redfish_command: SET chassis new indicator LED values
        community.general.redfish_command:
            category: Chassis
            baseuri: "{{ inventory_hostname }}:{{ ansible_port }}"         
            command: "{{ 'IndicatorLedOn' if item.IndicatorLED == 'Off' else 'IndicatorLedOff' }}"
            resource_id: "{{ item.Id }}"
            username: "{{ username }}"
            password: "{{ password }}"
        register: result
        with_items: "{{ ChassisLEDValues }}"
           
       
      - name: 3.0- Get chassis inventory
        community.general.redfish_info:
             category: Chassis
             command: GetChassisInventory
             baseuri: "{{ inventory_hostname }}:{{ ansible_port }}"
             username: "{{ username }}"
             password: "{{ password }}"
        register: ChassisInventory
             
      - debug:
           msg: "{{ ChassisInventory.redfish_facts.chassis.entries | json_query('[].{ChassisType: ChassisType, Id: Id, IndicatorLED: IndicatorLED}') }}"
