## Version 0.113
##
- hosts: OneViewManagedBmcs
  connection: local
  gather_facts: False
  vars:
          URL: "https://{{ inventory_hostname }}:{{ ansible_port }}"
          ChassisURI: "{{ URL }}/redfish/v1/Chassis"
          
  tasks:
          - name: 1- Discover chassis collection at standard root service /redfish/v1/Chassis
            uri:
                    url: "{{ ChassisURI }}"
                    return_content: yes
                    validate_certs: no
                    method: GET
                    headers:
                            X-Auth-Token: "{{ token }}"
                            accept: 'application/json'
                            content-type: 'application/json'
            register: ChassisInventory 
            
          - name: Save locations and print collection
            set_fact:
               ChassisLocationCollection: "{{ ChassisInventory.content | from_json 
                       | json_query('Members[].\"@odata.id\"') }}"
               
          - debug:
                msg="Chassis Collection => {{ ChassisLocationCollection }}"
                
          
          - name: 2- Retrieve and print selected properties of each chassis of the collection
            uri:
                    url: "{{ URL }}/{{ item }}"
                    return_content: yes
                    validate_certs: no
                    method: GET
                    headers:
                            X-Auth-Token: "{{ token }}"
                            accept: 'application/json'
                            content-type: 'application/json'
            with_items: "{{ ChassisLocationCollection }}"
            register: ChassisCollectionProperties
            
          - debug:
                msg: "{{ ChassisCollectionProperties.results | json_query('[].json.{IndicatorLED: IndicatorLED, Id: Id, ChassisType: ChassisType}') }}"
          


          
          