## Version 0.11
## 
## GET Security params using Ansible built-in Uri module


- hosts: OneViewManagedBmcs
  connection: local
  gather_facts: False
  vars:
          SecurityParamsUri: "https://{{ inventory_hostname }}:{{ ansible_port }}/redfish/v1/Managers/1/SecurityService/SecurityDashboard/SecurityParams?$expand=."
          
  tasks:
          - name: GET Security Parameters
            uri:
                    url: "{{ SecurityParamsUri }}"
                    return_content: yes
                    validate_certs: no
                    method: GET
                    headers:
                            X-Auth-Token: "FakeToken"
                            accept: 'application/json'
                            content-type: 'application/json'
            register: SecurityParams

          - debug: var=SecurityParams.content
            run_once: true
