apiVersion: v1
kind: Service
metadata:
  name: frontend-student76
spec:
  ports:
   - port: 3000
     name: http-fe
     protocol: TCP
     targetPort: 3000
  selector:
      app: frontend-student76
  #type: LoadBalancer
  type: NodePort
